# Конфиг на русском языке: https://github.com/snezhok69/sQuitJoin/tree/main

# If true, custom promises work
# If false, then the standard ones are enabled
enableJoinQuit: true
# If true, all messages are disabled
# If the custom messages are true, then they will be in priority, if false, then the standard ones will be in priority.
disableDefaultJoinQuit: false
joinMessage: '&8[&a+&8] &f%player%'
quitMessage: '&8[&4-&8] &f%player%'
# All sounds https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
joinSound: 'ENTITY_PLAYER_LEVELUP'
# Change the tone of the sound.
joinPitch: 1.0
successfullyreload:
  - '&a[sQuitJoin] &fУспешная перезагрузка &e%mc%&7mc'
nopermission:
  - '&a[sQuitJoin] &4У вас нет прав на перезагрузку плагина.'

